config/routes.rb
Rails.application.routes.draw do
  get 'main_features/home'
  get 'main_features/create'
  get 'main_features/results'
  root 'main_features#home'
  resources :polls

end

app/models/poll.rb
class Poll < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_features_controller.rb
class MainFeaturesController < ApplicationController
  def home
  end

  def create
  end

  def results
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  def new
    @poll = Poll.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_features_helper.rb
module MainFeaturesHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
    %head
        %title FeedbackApp
        = stylesheet_link_tag 'application', media: 'all'
        = javascript_include_tag 'application'
        = csrf_meta_tags
    %body
    /
        %header.navbar.navbar-fixed-top.navbar-inverse
        .container
            = link_to "sample app", '#', id: "logo"
            %nav
                %ul.nav.navbar-nav.navbar-right
                    %li= link_to "Home", '#'
                    %li= link_to "Help", '#'
                    %li= link_to "Log in", '#'
    .container
        = yield

app/views/main_features/create.html.erb
<h1>MainFeatures#create</h1>
<p>Find me in app/views/main_features/create.html.erb</p>

app/views/main_features/home.html.haml
%div{'ng-app' => 'feedback', 'ng-controller' => 'MainController'}  
  %h1 Feedback
  %p Group Decision Making Made Fun
  = link_to "New Poll", new_poll_path, class: "btn btn-default"
  %p {{test}}

  %ng-view

app/views/main_features/new_poll.html.haml
%div test
  %p test test

app/views/main_features/results.html.erb
<h1>MainFeatures#results</h1>
<p>Find me in app/views/main_features/results.html.erb</p>

app/views/polls/new.html.haml
%h1 New Poll
.row
    .col-md-6.col-md-offset-3
        = form_for(@poll) do |f|
            = f.label :question
            = f.text_field :question